# build.yml
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-windows

    runs-on: ${{ matrix.os }}
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DISABLE_METRICS: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@v4.1.2

      - name: Install system SDL2 packages
        if: runner.os != 'Windows'
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt update
            sudo apt install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev pkg-config
          fi

      - name: Setup vcpkg (Windows)
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: '5b1214315250939257ef5d62ecdcbca18cf4fb1c'

      - name: Configure CMake
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
              cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
          else
              cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          fi

      - name: Build project
        shell: bash
        run: |
          cmake --build build --config Release

      - name: Upload them artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-${{ runner.os }}
          path: build/**